/**
 * Tupper's Self-Referential Formula Core Utilities.
 * Uses BigInt to handle the massive integers generated by the formula.
 */

/**
 * Encodes a 1D array of pixel data (RGBA) into a Tupper constant `k`.
 * 
 * @param pixels Uint8ClampedArray from ImageData
 * @param width Image width
 * @param height Image height
 * @param threshold Brightness threshold (0-255) to determine black (1) or white (0)
 * @returns The huge Tupper constant `k` as a string
 */
export function encodeToTupper(pixels: Uint8ClampedArray, width: number, height: number, threshold: number = 128): string {
  let binStr = '';
  // Tupper's math reads from bottom to top, left to right.
  // In canvas/image data, (0,0) is top-left.
  // So x goes 0 to width-1, and for each x, y goes height-1 down to 0.
  
  for (let x = 0; x < width; x++) {
    for (let y = height - 1; y >= 0; y--) {
      const idx = (y * width + x) * 4;
      // Calculate perceptive luminance
      const r = pixels[idx];
      const g = pixels[idx + 1];
      const b = pixels[idx + 2];
      const luminance = 0.299 * r + 0.587 * g + 0.114 * b;
      
      // In Tupper's original formula, 1 is drawn (black), 0 is empty (white).
      // So if luminance is BELOW threshold, it is dark -> 1.
      const bit = luminance < threshold ? '1' : '0';
      // The first bit evaluated (x=0, y=height-1) goes to 2^0 position, so we just build a string 
      // where the first char is LSB. To use BigInt with base 2 parsing, the string needs MSB first.
      // So we prepend.
      binStr = bit + binStr;
    }
  }

  // Convert binary string to BigInt
  // For very large strings, binStr could be tens of thousands of characters.
  if (!binStr) return "0";
  
  // N = sum of bits * 2^i
  const N = BigInt('0b' + binStr);
  
  // k = N * height
  const k = N * BigInt(height);
  
  return k.toString();
}

/**
 * Decodes a Tupper constant `k` back into a 2D boolean grid (true = black, false = white).
 * 
 * @param kStr The constant `k` as a string
 * @param width The grid width
 * @param height The grid height
 * @returns A 2D array representing the monochrome grid (width x height)
 */
export function decodeFromTupper(kStr: string, width: number, height: number): boolean[][] {
  if (!kStr || kStr.trim() === '') {
    return Array.from({ length: width }, () => Array(height).fill(false));
  }

  try {
    const k = BigInt(kStr);
    const N = k / BigInt(height);
    
    const grid: boolean[][] = [];
    
    // N is the integer whose bit representation gives the pixels
    for (let x = 0; x < width; x++) {
      const column: boolean[] = [];
      for (let y = 0; y < height; y++) {
        // bit at index (x * height + y)
        const shift = BigInt(x * height + y);
        const bit = (N >> shift) & 1n;
        // In our array, column[0] represents bottom pixel (y=0 in Tupper Math)
        // We will return it such that grid[x][y] where y=0 is TOP to match Canvas easily if wanted,
        // Wait, let's keep it pure to Tupper: grid[x][0] is BOTTOM. 
        column.push(bit === 1n);
      }
      grid.push(column);
    }
    
    return grid;
  } catch (e) {
    console.error("Invalid Tupper constant k", e);
    // Return empty grid on failure
    return Array.from({ length: width }, () => Array(height).fill(false));
  }
}
